[package]
name = "omacull"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
eframe = { version = "0.36.2", default-features = false, features = ["wgpu", "wayland", "x11", "default_fonts"] }
egui = "0.36.2"
env_logger = "0.11.11"
log = "0.4.34"
omacull-engine = { version = "0.1.0", path = "../omacull-engine" }
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
